#
# Magic Lantern Core source files and rules
#

all:: autoexec.bin print_build_info

clean::
	$(call rm_files, *.o *.d *.i *.s autoexec autoexec.bin magiclantern magiclantern.bin)

CFLAGS += \
	-DCONFIG_MAGICLANTERN=1 \
	-DCONFIG_$(MODEL)=1 \
	-DCONFIG_$(MODEL)_$(FW_VERSION)=1 \
	-DRESTARTSTART=$(RESTARTSTART) \
	-DROMBASEADDR=$(ROMBASEADDR) \
	-DVERSION=\"$(VERSION)\" \
	-DCAMERA_MODEL=\"$(MODEL)\" \
	-DCONFIG_DEBUGMSG=$(CONFIG_DEBUGMSG) \
	-DCONFIG_FW_VERSION=$(FW_VERSION) \
	-DCURRENT_CAMERA_SIGNATURE=SIG_$(MODEL)_$(FW_VERSION)
